// ============================================================================
// Site Configuration — edit content here. Projects come from /projects.json.
// ============================================================================

export interface SiteConfig {
  title: string;
  description: string;
  language: string;
  github: string;
  linkedin: string;
  email: string;
}

export const siteConfig: SiteConfig = {
  title: "Zylen Saldahna — AI / ML Computer Science Student",
  description:
    "Final-year Computer Science student at the University of Greenwich specialising in AI and machine learning. Building intelligent systems — from agentic OS projects to dual-engine crime forecasting.",
  language: "en",
  github: "https://github.com/koro119",
  linkedin: "https://www.linkedin.com/in/zylen-saldahna-547003212",
  email: "koro119@gmail.com",
};

// ============================================================================
// Navigation
// ============================================================================

export interface NavItem {
  label: string;
  href: string;
}

export const navigationConfig: { logo: string; items: NavItem[] } = {
  logo: "zylen.dev",
  items: [
    { label: "About", href: "#about" },
    { label: "AI-Assisted", href: "#AI-assisted" },
    { label: "From Scratch", href: "#from-scratch" },
    { label: "Experiments", href: "#experiments" },
    { label: "My Setup", href: "#setup" },
    { label: "Work", href: "#work" },
    { label: "Making Of", href: "#making" },
  ],
};

// ============================================================================
// Hero
// ============================================================================

export interface HeroConfig {
  name: string;
  tagline: string;
  intro: string;
  ctaText: string;
  ctaHref: string;
  photo: string;
  stats: { value: string; label: string }[];
}

export const heroConfig: HeroConfig = {
  name: "Zylen Saldahna",
  tagline: "Final-year CS student · AI / ML focus · Building intelligent systems",
  intro:
    "I'm a final-year Computer Science student at the University of Greenwich, specialising in AI and machine learning. Ideas land and I start building the same week — some become shipped apps, others become findings. And I want what I build to be useful enough that someone would pay for it.",
  ctaText: "See what I've built",
  ctaHref: "#AI-assisted",
  photo: `${import.meta.env.BASE_URL}profile.jpg`,
  stats: [
    { value: "27", label: "Projects" },
    { value: "3", label: "Sections of work" },
    { value: "2019", label: "Started coding" },
  ],
};

// ============================================================================
// About
// ============================================================================

export interface QuizOption {
  label: string;
  points: { [archetype: string]: number };
}

export interface QuizQuestion {
  id: string;
  question: string;
  options: QuizOption[];
}

export interface AboutConfig {
  heading: string;
  paragraphs: string[];
  quizTitle: string;
  quizNote: string;
  quizIntro: string;
  archetypes: { [key: string]: { title: string; text: string } };
  questions: QuizQuestion[];
}

export const aboutConfig: AboutConfig = {
  heading: "About me",
  paragraphs: [
    "I build systems that combine software, hardware and models — from a dual-engine crime forecasting pipeline (XGBoost + a local LLM reading the news) to a personal agentic OS written in Rust.",
    "I move fast. The projects I ship, I design and direct end to end — the architecture, the direction and the review are mine — and I use every tool that gets me there faster. The fundamentals I write by hand, line by line. Both matter, and this site shows the difference.",
    "Useful is the bar I aim for — I'm money-motivated, but as a driver rather than a dirty word: I want the things I build to be useful enough that someone would pay for them. It's why my work mixes ambition (an agent that grows its own language) with pragmatism (a job-application tracker that reads live job APIs).",
  ],
  quizTitle: "A small project that analyses you",
  quizIntro:
    "Answer a few questions about how you work and this little model will analyse you — because why not. It's a small rules-based project I built (a weighted scoring script, honestly), not a cloud API.",
  quizNote: "Readout generated by a small model I built — weighted scoring over four dimensions. No LLM, just rules.",
  archetypes: {
    velocity: {
      title: "The Velocity Builder",
      text: "You optimise for shipped over perfect. You'd rather have a working thing today and a better one next week than a perfect one never. You use AI tools as a force multiplier and you're unapologetic about it — because the alternative is not building at all.",
    },
    idea: {
      title: "The Idea Engine",
      text: "Your bottleneck was never ideas — it's deciding which one to chase this week. You generate constantly, prototype fast, and let the market (or the grade) tell you what's worth finishing. The graveyard of half-built projects is a feature, not a bug.",
    },
    systems: {
      title: "The Systems Thinker",
      text: "You don't build features, you build machines that build features. Agents, pipelines, engines — you like the architecture layer, where the interesting leverage lives. You'll happily spend a week making something that saves you an hour a day, forever.",
    },
    money: {
      title: "The Pragmatist",
      text: "You ask 'who would pay for this?' before you ask 'is this cool?'. You value outcomes — revenue, grades, real users — and you structure your work around proving value, not just demonstrating skill.",
    },
  },
  questions: [
    {
      id: "speed",
      question: "When an idea lands, what do you do?",
      options: [
        { label: "Start building the same week — imperfect and fast", points: { velocity: 2, money: 1 } },
        { label: "Sketch it, plan it, then build", points: { systems: 2, idea: 1 } },
        { label: "Let it sit while three new ideas land", points: { idea: 2 } },
        { label: "Ask who'd pay for it before writing code", points: { money: 2, velocity: 1 } },
      ],
    },
    {
      id: "ai",
      question: "AI coding tools are…",
      options: [
        { label: "A force multiplier — I ship 5x faster", points: { velocity: 2, money: 1 } },
        { label: "A co-architect — great for hard systems problems", points: { systems: 2 } },
        { label: "Fuel for ideas — I build things I'd never have time for", points: { idea: 2 } },
        { label: "Careful with them — fundamentals come from writing it myself", points: { systems: 1, velocity: 1 } },
      ],
    },
    {
      id: "motivation",
      question: "What actually gets you out of bed?",
      options: [
        { label: "Money and outcomes — value you can measure", points: { money: 2 } },
        { label: "A problem so interesting I can't stop thinking about it", points: { idea: 2, systems: 1 } },
        { label: "Shipping — that green 'deployed' button", points: { velocity: 2 } },
        { label: "Building the machine that builds things", points: { systems: 2 } },
      ],
    },
    {
      id: "style",
      question: "Your natural work style?",
      options: [
        { label: "Jump between projects — energy decides the queue", points: { idea: 2, velocity: 1 } },
        { label: "Deep focus on one thing until it's done", points: { velocity: 1, systems: 1 } },
        { label: "Systemise everything — processes over heroics", points: { systems: 2 } },
        { label: "Work backwards from the outcome that pays", points: { money: 2 } },
      ],
    },
  ],
};

// ============================================================================
// My Setup
// ============================================================================

export interface SetupItem {
  kicker: string;
  title: string;
  text: string;
}

export interface SetupConfig {
  heading: string;
  subtitle: string;
  items: SetupItem[];
}

export const setupConfig: SetupConfig = {
  heading: "My setup",
  subtitle:
    "The tools behind everything on this page — a mix of cloud and fully-local AI.",
  items: [
    {
      kicker: "Cloud",
      title: "DeepSeek Harness",
      text: "The AI coding harness I build with. I direct the plan and review the output; it turns that direction into a working site at speed.",
    },
    {
      kicker: "Local",
      title: "LM Studio",
      text: "Local AI that runs entirely on my own machine — no cloud, no API keys, no round-trip latency. The model stays mine.",
    },
    {
      kicker: "Model",
      title: "Qwen 3.5 9B · MLX",
      text: "My local model: 9 billion parameters in MLX format, running through LM Studio on Apple Silicon.",
    },
  ],
};

// ============================================================================
// Work Experience
// ============================================================================

export interface WorkRole {
  role: string;
  place: string;
  dates: string;
  points: string[];
}

export interface WorkConfig {
  heading: string;
  statement: string;
  intro: string;
  roles: WorkRole[];
}

export const workConfig: WorkConfig = {
  heading: "I am not just 1s & 0s",
  statement:
    "Before the models, there was the real world — and it taught me things a compiler never will.",
  intro:
    "I've worked real jobs since before university — hospitality, service, supervision. It's the part of my background that's easy to leave off a CS portfolio, but it's where the work ethic came from. Responsibility, pressure, customers, earning my own money — all of it.",
  roles: [
    {
      role: "Supervisor",
      place: "Farmer J · London",
      dates: "May 2023 → Present",
      points: [
        "Started as a barista and worked up to running the shift — opening, lunch service and peak-period planning through team briefings and position allocation.",
        "Train new staff, de-escalate conflict, and keep the team moving through high-volume corporate orders.",
        "Oversee food production for the next day and keep inventory right.",
      ],
    },
    {
      role: "Bartender",
      place: "Oasis Lounge by Melaya · Leicester",
      dates: "Nov 2022 → Apr 2023",
      points: [
        "Walked in with no experience, learned the classic cocktail list, then ran the bar solo when it mattered.",
        "Crossed into the kitchen — cheese and deli boards, crepes, desserts — and covered every shift type.",
        "Stock control, end-of-day cash reconciliation, plus social media and event promotion.",
      ],
    },
    {
      role: "Barista",
      place: "The Real Eating Company · Marble Arch",
      dates: "Jan 2022 → Aug 2022",
      points: [
        "Went from basics to latte art in about four months, and picked up the morning-chef role for English breakfasts.",
        "Opening and closing the shop, stock and ordering, and covering other locations when short-staffed.",
        "The unglamorous part nobody sees: deep-cleaning and calibrating the espresso machine and grinder.",
      ],
    },
    {
      role: "Barista / Bartender",
      place: "Marriott Grosvenor Square · Marble Arch",
      dates: "Sep 2021 → Dec 2021",
      points: [
        "Started on breakfast service — serving, cleaning, setting tables and restocking.",
        "Trained up to the coffee bar, where I first learned to steam milk properly for different drinks.",
      ],
    },
    {
      role: "Bubble Tea Barista",
      place: "Bubbleology · Notting Hill",
      dates: "Jul 2021 → Sep 2021",
      points: [
        "Early days of working life: learned responsibility and accountability, fast.",
        "Tapioca prep is a multi-stage process with exact measurements — taught me to work methodically.",
        "Ran peak times both solo and in a team, and opened and shut the shop on my own.",
      ],
    },
    {
      role: "Customer Service",
      place: "Knights Sound & Lights",
      dates: "Mar 2019",
      points: [
        "First taste of work: restocking, labelling, ordering, customers and Microsoft Office.",
        "Keeping the store clean and running — the fundamentals before everything else.",
      ],
    },
  ],
};

// ============================================================================
// Making of This Website
// ============================================================================

export interface MakingStep {
  phase: string;
  title: string;
  text: string;
}

export interface MakingConfig {
  heading: string;
  intro: string;
  honest: string;
  steps: MakingStep[];
  closing: string;
}

export const makingConfig: MakingConfig = {
  heading: "The making of this website",
  intro:
    "A behind-the-scenes look at how this site was planned and built — including the parts most portfolios leave out.",
  honest:
    "I planned this site myself — the structure, the content, every design decision — then built it fast with the tools I use every day. The result is a working site in a fraction of the time, and the process itself is the case study below.",
  steps: [
    {
      phase: "01 · Concept",
      title: "Plan first, code second",
      text: "The site started as a written plan — section by section, prompt by prompt. Structure: Hero, AI-Assisted, From Scratch, Experiments, Work, Making Of. Every section had a purpose before a single line of code existed.",
    },
    {
      phase: "02 · Archive",
      title: "The projects feed",
      text: "The real work was the archive: 27 repos, each with a README and tags — AI-assisted, from-scratch, conceptual-experiment. projects.json is the machine-readable index that feeds this site. Content first, then the page.",
    },
    {
      phase: "03 · Build",
      title: "Building the frontend",
      text: "I built the frontend against the plan: React + Vite + Tailwind, a slate-and-teal theme on squared glass panels, scroll-reveal animations, and a data-driven project grid.",
    },
    {
      phase: "04 · Iterate",
      title: "Direction, review, polish",
      text: "The part that isn't magic: iteration. Theme decisions, section naming ('Essential Experiments' → 'Conceptual Experiments'), the 'not just 1s & 0s' line in the Work section — all direction. The tool executes; the taste is mine.",
    },
    {
      phase: "05 · Ship",
      title: "Deploy and maintain",
      text: "This site is itself a project in the archive — proof that the process ships. It's live on GitHub Pages, and the projects feed means updating it is editing one JSON file.",
    },
  ],
  closing:
    "The takeaway: the thinking is the product. Good tools make you faster, but the direction and the decisions are what actually ship.",
};

// ============================================================================
// Footer
// ============================================================================

export interface FooterConfig {
  tagline: string;
  copyright: string;
}

export const footerConfig: FooterConfig = {
  tagline: "Final-year Computer Science student — building intelligent systems that ship.",
  copyright: `© ${new Date().getFullYear()} Zylen Saldahna.`,
};
